export const COUNTRIES = [
  { value: "all", label: "All countries" },
  { value: "US", label: "United States" },
  { value: "IN", label: "India" },
  { value: "GB", label: "United Kingdom" },
  { value: "CA", label: "Canada" },
  { value: "AU", label: "Australia" },
  { value: "FR", label: "France" },
  { value: "DE", label: "Germany" },
  { value: "IT", label: "Italy" },
  { value: "ES", label: "Spain" },
  { value: "JP", label: "Japan" },
  { value: "KR", label: "South Korea" },
  { value: "CN", label: "China" },
  { value: "HK", label: "Hong Kong" },
  { value: "BR", label: "Brazil" },
  { value: "MX", label: "Mexico" },
  { value: "RU", label: "Russia" },
  { value: "SE", label: "Sweden" },
  { value: "NG", label: "Nigeria" },
];